#!/bin/bash

install_programs() {
    while IFS= read -r program; do
        if ! dpkg -l | grep -q "$program"; then
            sudo apt-get install -y "$program"
        else
            echo "$program is already installed"
        fi
    done < "$1"
}

# Update package list and upgrade all packages
sudo apt-get update
sudo apt-get upgrade -y

bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

if [[ -z "$1" ]]; then
    echo "Please provide a file containing the list of programs to install."
    exit 1
fi

install_programs "$1"

